// Copyright 2020 ConsenSys Software Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by goff (v0.3.11) DO NOT EDIT

package bls12381

// /!\ WARNING /!\
// this code has not been audited and is provided as-is. In particular,
// there is no security guarantees such as constant time implementation
// or side-channel attack resistance
// /!\ WARNING /!\

func mul(z, x, y, mod *Element, modinv uint64) {
	_mulGeneric(z, x, y, mod, modinv)
}

func add(z, x, y, mod *Element) {
	_addGeneric(z, x, y, mod)
}

func sub(z, x, y, mod *Element) {
	_subGeneric(z, x, y, mod)
}
